version: '3.8'

services:
  api:
    build: .
    image: flask-grapql:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 5000:5000

  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./sql/table.sql:/docker-entrypoint-initdb.d/table.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_data
